---

name: Lint

on:
  push:

jobs:
  isort:
    runs-on: ubuntu-latest
    name: Check import order
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate
        uses: ./
        id: isort
